name: Release binaries
on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-11
            xcode: 13.2.1
          - os: macos-11
            xcode: 12.4
          - os: macos-10.15
            xcode: 11.3.1
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build dependencies
        run: ./build_depends.sh

  release:
    runs-on: macos-11
    needs: build
    steps:
      - run: echo release version ${{ inputs.newVersion }} 
