name: Release binaries
on:
  workflow_dispatch:
    inputs:
      newVersion:
        type: string
        description: 'Release version'
        required: true
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11]
        xcode: [11.3.1, 12.4, 13.2.1]
        exclude:
          - os: macos-10.15
            xcode: 12.4
          - os: macos-10.15
            xcode: 13.2.1
          - os: macos-11
            xcode: 11.3.1
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build dependencies
        run: ./build_depends.sh

  release:
    runs-on: macos-11
    needs: build
    steps:
      - run: echo release version ${{ inputs.newVersion }} 
